# Generated by Django 2.2.5 on 2022-01-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank_data',
            name='user_rank',
        ),
    ]
